/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Repository, ref, and Fabro workflow selector materialized when the automation starts.
 */
export interface AutomationTarget {
    /**
     * GitHub owner/repo slug.
     */
    'repository': string;
    /**
     * Branch, tag, or SHA selector to check out.
     */
    'ref': string;
    /**
     * Fabro workflow slug or relative workflow path.
     */
    'workflow': string;
}
