/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AutomationScheduleTrigger {
    'id': string;
    'type': AutomationScheduleTriggerTypeEnum;
    'enabled'?: boolean;
    /**
     * Five-field cron expression accepted by croner.
     */
    'expression': string;
}

export const AutomationScheduleTriggerTypeEnum = {
    SCHEDULE: 'schedule'
} as const;

export type AutomationScheduleTriggerTypeEnum = typeof AutomationScheduleTriggerTypeEnum[keyof typeof AutomationScheduleTriggerTypeEnum];
