/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RunError } from './run-error';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatus } from './run-status';

/**
 * Current status of a run with optional error and queue position.
 */
export interface RunStatusResponse {
    /**
     * Unique run identifier (ULID).
     */
    'id': string;
    /**
     * Non-blank resolved run title.
     */
    'title': string;
    'status': RunStatus;
    'error'?: RunError;
    /**
     * Position in the queue (1-based). Only present when the status kind is `queued`.
     */
    'queue_position'?: number;
    'pending_control'?: RunControlAction | null;
    /**
     * Timestamp when the run was created.
     */
    'created_at': string;
    /**
     * Public URL where the run can be viewed in the web UI. Present when the server has the web UI enabled (`server.web.enabled = true`) and `server.web.url` is non-empty; absent otherwise. 
     */
    'web_url'?: string;
}



