/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BoardColumn } from './board-column';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryReference } from './repository-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RunPullRequest } from './run-pull-request';
// May contain unused imports in some cases
// @ts-ignore
import type { RunQuestion } from './run-question';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSandbox } from './run-sandbox';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatus } from './run-status';

/**
 * Canonical run summary shown in the board view, extended with board-specific metadata.
 */
export interface RunListItem {
    /**
     * Unique run identifier (ULID).
     */
    'run_id': string;
    'workflow_name'?: string | null;
    'workflow_slug'?: string | null;
    'goal': string;
    'repository': RepositoryReference;
    /**
     * Non-blank resolved run title.
     */
    'title': string;
    'status': RunStatus;
    'labels': { [key: string]: string; };
    'source_directory'?: string | null;
    'in_place'?: boolean;
    'repo_origin_url'?: string | null;
    'start_time'?: string | null;
    'pending_control'?: RunControlAction | null;
    'duration_ms'?: number | null;
    'elapsed_secs'?: number | null;
    'total_usd_micros'?: number | null;
    'column': BoardColumn;
    'pull_request'?: RunPullRequest;
    'sandbox'?: RunSandbox;
    'question'?: RunQuestion;
    /**
     * Timestamp when the run was created.
     */
    'created_at': string;
    /**
     * Timestamp of the most recent event applied to the run\'s projection. Null until the first event is recorded.
     */
    'last_event_at'?: string | null;
}



