/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxProvider } from './sandbox-provider';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxResources } from './sandbox-resources';

/**
 * Canonical sandbox environment record for a run.
 */
export interface RunSandbox {
    'provider': SandboxProvider;
    /**
     * Fabro sandbox control identifier used for reconnect, terminal, and delete operations.
     */
    'id': string;
    /**
     * Path where the run executed inside the sandbox.
     */
    'working_directory': string;
    /**
     * Whether the provider cloned the repository into the sandbox, or null while unknown.
     */
    'repo_cloned'?: boolean | null;
    /**
     * Repository origin cloned into the sandbox when available.
     */
    'clone_origin_url'?: string | null;
    /**
     * Repository branch cloned into the sandbox when available.
     */
    'clone_branch'?: string | null;
    'resources'?: SandboxResources | null;
}
