/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxProvider } from './sandbox-provider';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxResources } from './sandbox-resources';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxState } from './sandbox-state';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxTimestamps } from './sandbox-timestamps';

/**
 * Provider-neutral details about the sandbox owned by a run.
 */
export interface SandboxDetails {
    'provider': SandboxProvider;
    /**
     * Fabro sandbox control identifier used for reconnect, terminal, and delete operations.
     */
    'id': string;
    /**
     * Path where the run executed inside the sandbox.
     */
    'working_directory': string;
    'state': SandboxState;
    /**
     * Original provider state string before normalization. Display/debugging only; UI behavior keys off `state`.
     */
    'native_state'?: string;
    /**
     * Provider region or target. Null for local-style providers.
     */
    'region'?: string;
    /**
     * Container image or sandbox snapshot identifier.
     */
    'image'?: string;
    'resources': SandboxResources;
    /**
     * Provider-reported labels.
     */
    'labels': { [key: string]: string; };
    'timestamps': SandboxTimestamps;
}



